spring:
  application:
    name: zuulgateway

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

zuul:
  routes:
    magasinMs:
      path: /api-magasin/**
      service-id: magasinMs

#    magasinMs:
#      path: /api-magasin/**
#      service-id: magasinMs

#    magasinMs:
#      path: /api-magasin/**
#      service-id: magasinMs

#    magasinMs:
#      path: /api-magasin/**
#      service-id: magasinMs
